# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0128dc08cfe41c42f2d532ded090db1881e5fe3b0746141657f45289c84f533d0cef5fd3f514242907da0c47230ec702101a5f7ba011183a9002780998db34d7

test:
  secret_key_base: 874f921a1d8111dc8b96d3988054a9d74bf5c03abe3e257523470b72a1609ed3fc6acdb37db64909f79358fe923cf5ea58a4e99db05042d732bfc6c403f0fa09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
